- hosts: all
  become: true
  pre_tasks:
    - name: update repository index (CentOS)
      tags: always
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"

    - name: install updates (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: servers
  become: true
  roles:
    - servers

- hosts: server_centOS
  become: true
  roles:
    - server_centOS

- hosts: file_server
  become: true
  roles:
    - file_server
